CR-1208 | Pointing to the new release version of census-int-common-service
ONSdigital/census-contact-centre-service pull request #107
Opened 2020-09-22 14:37 UTC by akritisinhaa

The EstabType has been update in census-int-common-service and also OTHER type has been modified to fix an existing bug. A new version of census-int-common-service has been released which is 0.0.66. Updating pom.xml to point to this new version.

For more details on the changes in census-int-common-service please have a look at https://collaborate2.ons.gov.uk/jira/browse/CR-1208.

2020-09-23 13:50 UTC, rpcatling requested changes
just a couple of minor naming changes requested.

2020-09-23 13:50 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplModifyCaseTest.java
> +    verifyModifyAddress(CaseType.HH, EstabType.HOUSEHOLD, EstabType.RESIDENTIAL_BOAT.getCode());
method name is now misleading. please change it

2020-09-23 13:50 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplModifyCaseTest.java
> +    verifyModifyAddress(CaseType.SPG, EstabType.EMBASSY, EstabType.MILITARY_SFA.getCode());
method name is now misleading. please change it

2020-09-24 06:51 UTC, rpcatling approved these changes
All good

2020-09-24 09:53 UTC, MartinHumphrey approved these changes

2020-09-24 11:18 UTC, merged