Adding a new query parameter to two calls
ONSdigital/census-contact-centre-service pull request #119
Opened 2020-10-27 15:50 UTC by georgecodes

# Motivation and Context
A downstream API has additional requirements for requests now.

# What has changed
Requests to /addresses and /addresses/postcode/{postcode} in AI now have a includeauxiliarysearch query param which we need to pass.

# How to test?
The relevant unit tests have been updated.

# Links
https://collaborate2.ons.gov.uk/jira/browse/CR-1107

2020-10-28 08:35 UTC, rpcatling requested changes
Although the code is OK, for me running locally the cucumber won't succeed since with the extra flag AIMS is coming back with either 5xx or 429 errors.    I suspect this hasn't been tested in DEV which also needs to happen.

2020-11-09 11:36 UTC, rpcatling approved these changes

2020-11-09 11:36 UTC, rpcatling commented
RH-DEV now has the auxilliary index, so cucumber will work

2020-11-10 13:25 UTC, cookel2 approved these changes
looks good George

2020-11-10 13:35 UTC, merged