CR-1305 Removed code to check that title is suppled on individual ful…
ONSdigital/census-contact-centre-service pull request #122
Opened 2020-10-30 12:15 UTC by PeterBochel

…filment requests

2020-10-30 15:26 UTC, rpcatling requested changes
just want another unit test!

2020-10-30 15:26 UTC, rpcatling commented on src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/service/impl/CaseServiceImplFulfilmentTest.java
> -    doVerifyFulfilmentRequestByPostFailsValidation(
I think we could do with a unit tests that succeeds for fulfilment by POST for individual where title is null or blank.

2020-11-03 10:00 UTC, rpcatling approved these changes

2020-11-04 10:43 UTC, cookel2 approved these changes
looks good Peter

2020-11-04 10:44 UTC, merged